import { Track } from 'react-native-track-player';

export const playListData: Track[] = [
  {
    id: 1,
    title: 'Daytona',
    artist: 'Karan Aujla',
    album: 'album_1',
    artwork: 'https://images.genius.com/8951cbdba253d5e5d64a84045600b618.1000x1000x1.jpg',
    url: require('../assets/Daytona.mp3'),
  },
  {
    id: 2,
    title: 'For A Reason',
    artist: 'Karan Aujla',
    album: 'album_1',
    artwork: 'https://th.bing.com/th/id/OIP.KToDdFA0LZJdLf0ytsG9YgHaEK?w=295&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
    url: require('../assets/ForAReason.mp3'),
  },
  {
    id: 3,
    title: 'Balenci',
    artist: 'Shubh',
    album: 'album_2',
    artwork: 'https://c.saavncdn.com/459/Balenci-Punjabi-2025-20250823083308-500x500.jpg',
    url: require('../assets/Balenci.mp3'),
  },
  {
    id: 4,
    title: 'Haseen',
    artist: 'Talwinder',
    album: 'album_3',
    artwork: 'https://i.ytimg.com/vi/IltsOcCj1Ak/maxresdefault.jpg',
    url: require('../assets/Haseen.mp3'),
  },
  {
    id: 5,
    title: 'I Really Do',
    artist: 'Karan Aujla',
    album: 'album_1',
    artwork: 'https://images.genius.com/8951cbdba253d5e5d64a84045600b618.1000x1000x1.jpg',
    url: require('../assets/IReallyDo.mp3'),
  },
  {
    id: 6,
    title: 'Move On',
    artist: 'Prem Dhillon',
    album: 'album_4',
    artwork: 'https://i.ytimg.com/vi/42dmxaRZDdM/maxresdefault.jpg',
    url: require('../assets/Moveon.mp3'),
  },
  {
    id: 7,
    title: 'Mulaqat',
    artist: 'Arjan Dhillon',
    album: 'album_5',
    artwork: 'https://i.ytimg.com/vi/KUeQDTX6D5o/maxresdefault.jpg',
    url: require('../assets/Mulaqat.mp3'),
  },
  {
    id: 8,
    title: 'Naviour',
    artist: 'Navaan Sandhu',
    album: 'album_6',
    artwork: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/4e/0c/d2/4e0cd29d-f2c3-0d41-c33e-9ab5c9acf396/25UM1IM43859.rgb.jpg/800x800cc.jpg',
    url: require('../assets/Naviour.mp3'),
  },
  {
    id: 9,
    title: 'Saware',
    artist: 'Arijit Singh',
    album: 'album_7',
    artwork: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/4e/0c/d2/4e0cd29d-f2c3-0d41-c33e-9ab5c9acf396/25UM1IM43859.rgb.jpg/800x800cc.jpg',
    url: require('../assets/Saware.mp3'),
  },
]
